version: 0.0
os: linux

files:
  - source: /
    destination: /root/kokonut_backend/
    overwrite: yes
    
hooks:
# 서버를 중지하는 스크립트
#  ApplicationStop:
#    - location: script/stop_server.sh
#      timeout: 60
#      runas: root

# 종속성을 설치하는 스크립트
#  BeforeInstall:
#    - location: script/install_dependencies.sh
#      timeout: 300
#      runas: root

# 애플리케이션을 시작하는 스크립트
  AfterInstall:
    - location: script/start.sh
      timeout: 300
      runas: root

# 모든 파일과 디렉토리를 root 사용자와 root 그룹으로 설정하는 권한 설정
permissions:
  - object: "/"
    pattern: "**"
    owner: root
    group: root