version: 0.2
phases:
  #install:
  #  commands:
  #    - npm install
  #pre_build:
  #  commands:
  #    - npm run lint
  #   - command
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(basename ./build/libs/*.jar)
      - pwd
      - ls -al
      - aws s3 cp --recursive dist/ s3://kokonut-server-update-20230213/upload/
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
cache:
  paths:
    - '/root/.gradle/caches/**/*'