server:
  port: '8050'

# JPA Setting
spring:
  datasource: #DB
    kokonut:
      url: jdbc:mariadb://${DOCKER_DB_HOST}:${DOCKER_DB_PORT}/${KOKONUT_DB_DBNAME}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${DOCKER_DB_USERNAME}
      password: ${DOCKER_DB_PASSWORD}
    kokonut-user:
      url: jdbc:mariadb://${DOCKER_DB_HOST}:${DOCKER_DB_PORT}/${KOKONUT_DB_USER}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${DOCKER_DB_USERNAME}
      password: ${DOCKER_DB_PASSWORD}
    kokonut-dormant:
      url: jdbc:mariadb://${DOCKER_DB_HOST}:${DOCKER_DB_PORT}/${KOKONUT_DB_DORMANT}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${DOCKER_DB_USERNAME}
      password: ${DOCKER_DB_PASSWORD}
    kokonut-remove:
      url: jdbc:mariadb://${DOCKER_DB_HOST}:${DOCKER_DB_PORT}/${KOKONUT_DB_REMOVE}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${DOCKER_DB_USERNAME}
      password: ${DOCKER_DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: '6379'
  data:
    redis:
      repositories:
        enabled: false

#Custom
kokonut:
  aws:
    # AWS S3
    s3:
      url: ${KOKONUT_AWS_S3_URL}
      bucket: ${KOKONUT_AWS_S3_BUCKET}
      access: ${KOKONUT_AWS_S3_ACCESS}
      secret: ${KOKONUT_AWS_S3_SECRET}

      # S3 버킷 폴더
      businessS3Folder: ${KOKONUT_AWS_S3_BUSINESSS3FOLDER}
      qnaS3Folder: ${KOKONUT_AWS_S3_QNAS3FOLDER}
      
    # AWS KMS
    kms:
      secret: ${KOKONUT_AWS_KMS_SECRET}
      access: ${KOKONUT_AWS_KMS_ACCESS}
      id: ${KOKONUT_AWS_KMS_ID}

  # JWT_SECRET_STRING : echo 'spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial' | base64
  jwt:
    secret: ${KOKONUT_JWT_SECRET}

  # 프론트 로컬서버
  front:
    server:
      domain: ${KOKONUT_FRONT_SERVER_DOMAIN}

  # 로컬IP
  otp:
    hostUrl: ${KOKONUT_OTP_URL}

  # 메일주소
  mail:
    host: ${KOKONUT_MAIL_HOST}

  # iamport 관련 값
  iamport:
    key: ${KOKONUT_IAMPORT_KEY}
    secret: ${KOKONUT_IAMPORT_SECRET}

  # niceId 관련 필요한 값
  nice:
    id: ${KOKONUT_NICE_ID}
    secret: ${KOKONUT_NICE_SECRET}
    product: ${KOKONUT_NICE_PRODUCT}
    access: ${KOKONUT_NICE_ACCESS}

  # naver cloud 관련 값
  ncloud:
    serviceId: ${KOKONUT_NCLOUD_SERVICEID}
    accessKey: ${KOKONUT_NCLOUD_ACCESSKEY}
    secretKey: ${KOKONUT_NCLOUD_SECRETKEY}
    primaryKey: ${KOKONUT_NCLOUD_PRIMARYKEY}
    categoryCode: ${KOKONUT_NCLOUD_CATEGORYCODE}

  #stibee
  stibee:
    apiKey: ${KOKONUT_STIBEE_APIKEY}